task:
  model:
    dropout_rate: 0.1
  init_checkpoint: '/tmp/tfrbert/uncased_L-12_H-768_A-12/bert_model.ckpt'
  train_data:
    drop_remainder: true
    global_batch_size: 4
    input_path: '/tmp/tfrbert/data/antique_train_seq_64_elwc.tfrecords'
    is_training: true
    seq_length: 64
    label_type: 'int'
    label_feature_name: 'relevance'
    list_size: 10
  validation_data:
    drop_remainder: false
    global_batch_size: 4
    input_path: '/tmp/tfrbert/data/antique_test_seq_64_elwc.tfrecords'
    is_training: false
    seq_length: 64
    label_type: 'int'
    label_feature_name: 'relevance'
    list_size: 10
  loss: 'softmax_loss'
  output_preds: false
trainer:
  checkpoint_interval: 500
  optimizer_config:
    learning_rate:
      polynomial:
        # 100% of train_steps.
        decay_steps: 10000
        end_learning_rate: 0.0
        initial_learning_rate: 3.0e-05
        power: 1.0
      type: polynomial
    optimizer:
      type: adamw
    warmup:
      polynomial:
        power: 1
        # ~10% of train_steps.
        warmup_steps: 1000
      type: polynomial
  steps_per_loop: 50
  summary_interval: 50
  train_steps: 10000
  validation_interval: 50
  validation_steps: -1
  best_checkpoint_export_subdir: 'best_ckpt'
  best_checkpoint_eval_metric: 'MAP'
  best_checkpoint_metric_comp: 'higher'
